// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVJV5GhGZhNZKE_2B1nbkUDhxIsOTqLFc',
    appId: '1:1050485803240:web:3cf17fdf0ec94f0f91615d',
    messagingSenderId: '1050485803240',
    projectId: 'habit-tracker-bc361',
    authDomain: 'habit-tracker-bc361.firebaseapp.com',
    storageBucket: 'habit-tracker-bc361.firebasestorage.app',
    measurementId: 'G-X8KRLRXFDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFE82jBNAykT7XSfI6PcscwME8TIuyo3s',
    appId: '1:1050485803240:android:62282817270b9bce91615d',
    messagingSenderId: '1050485803240',
    projectId: 'habit-tracker-bc361',
    storageBucket: 'habit-tracker-bc361.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXZk1hLsxdvFp8aP636PajrvILrJzC9pA',
    appId: '1:1050485803240:ios:f51126616731abc791615d',
    messagingSenderId: '1050485803240',
    projectId: 'habit-tracker-bc361',
    storageBucket: 'habit-tracker-bc361.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXZk1hLsxdvFp8aP636PajrvILrJzC9pA',
    appId: '1:1050485803240:ios:f51126616731abc791615d',
    messagingSenderId: '1050485803240',
    projectId: 'habit-tracker-bc361',
    storageBucket: 'habit-tracker-bc361.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVJV5GhGZhNZKE_2B1nbkUDhxIsOTqLFc',
    appId: '1:1050485803240:web:4cb3450743192f4991615d',
    messagingSenderId: '1050485803240',
    projectId: 'habit-tracker-bc361',
    authDomain: 'habit-tracker-bc361.firebaseapp.com',
    storageBucket: 'habit-tracker-bc361.firebasestorage.app',
    measurementId: 'G-MSTZ775Y6T',
  );

}